### ISSUE TITLE
`estimatefees` has changed in CLN version v23.05

### ISSUE THREAD

**Issue by tonyaldon** [nbd-wtf/trustedcoin#20]
`estimatefees` has changed in CLN version v23.05.

See deprecated section in https://github.com/ElementsProject/lightning/blob/master/CHANGELOG.md#23051---2023-06-05-austin-texas-agreementatxa-ii.

The new spec is (https://github.com/ElementsProject/lightning/blob/master/doc/PLUGINS.md#estimatefees):

`estimatefees`

Polled by `lightningd` to get the current feerate, all values must be passed in sat/kVB.

The plugin must return `feerate_floor` (e.g. 1000 if mempool is
empty), and an array of 0 or more `feerates`.  Each element of
`feerates` is an object with `blocks` and `feerate`, in
ascending-blocks order, for example:

```
{
	"feerate_floor": <sat per kVB>,
	"feerates": {
		{ "blocks": 2, "feerate": <sat per kVB> },
		{ "blocks": 6, "feerate": <sat per kVB> },
		{ "blocks": 12, "feerate": <sat per kVB> }
		{ "blocks": 100, "feerate": <sat per kVB> }
	}
}
```

lightningd will currently linearly interpolate to estimate between given blocks (it will not extrapolate, but use the min/max blocks values).

**Comment by fiatjaf** [comment]
If anyone wants to send a pull request, that will be great.

**Comment by cryptoteun** [comment]
Anybody who already take a look ont his one? It appears to be broken in 24.05. I get the following error:
` **BROKEN** lightningd: DEPRECATED API USED estimatefeesv1 `

Or do I jump to the wrong conclusion?

**Comment by fiatjaf** [comment]
It's definitely broken and waiting for your pull request that fixes it!

**Comment by 1ma** [comment]
Alright, let's do this. https://github.com/nbd-wtf/trustedcoin/pull/28

How hard can it be.

![rabbit](https://github.com/user-attachments/assets/03abf7fd-7877-4aa2-b268-417f7af9fb6f)
