### ISSUE TITLE
Trustedcoin is incompatible with bitcoin 28.0

### ISSUE THREAD

**Issue by erikarvstedt** [nbd-wtf/trustedcoin#33]
When running bitcoin 28.0, trustedcoin fails with error: 
```
plugin-trustedcoin bitcoind RPC backend settings detected, but failed to connect, will keep trying to use it though.
```
This is due to a format change in the response to `getnetworkinfo` in bitcoind 28.0.

## Fix
Update `btcsuite/btcd` in trustedcoin to a version that includes this PR: https://github.com/btcsuite/btcd/pull/2245

I tried this by running `go get github.com/btcsuite/btcd@67b8efd3ba53b60ff0eba5d79babe2c3d82f6c54`, but then I got build errors:
```
../../go/pkg/mod/github.com/lightningnetwork/lnd@v0.18.2-beta/keychain/btcwallet.go:451:9: not enough return values
	have ([]byte)
	want ([]byte, error)
../../go/pkg/mod/github.com/lightningnetwork/lnd@v0.18.2-beta/keychain/signer.go:88:9: not enough return values
	have ([]byte)
	want ([]byte, error)
```

## Meta

This bug is currently blocking the next nix-bitcoin release (https://github.com/fort-nix/nix-bitcoin/pull/744).
Would be great if you could provide a quick fix.

**Comment by 1ma** [comment]
Yeah, I found that compilation error while trying to update the project dependencies. `lightningnetwork/lnd` has a fix for the latest version of btcd in master, but it's not tagged yet.

lightningd-gjson-rpc also needs a fix, but fiatjaf moves fast:

```
# github.com/fiatjaf/lightningd-gjson-rpc
../../go/pkg/mod/github.com/fiatjaf/lightningd-gjson-rpc@v1.6.3/invoice.go:98:11: not enough return values
        have ([]byte)
        want ([]byte, error)
../../go/pkg/mod/github.com/fiatjaf/lightningd-gjson-rpc@v1.6.3/invoice.go:210:11: not enough return values
        have ([]byte)
        want ([]byte, error)
make: *** [Makefile:2: trustedcoin] Error 1
```

@fiatjaf if you're ok with it we can tag a fix in lightningd-gjson-rpc and depend on latest commit of lightningnetwork/lnd. I tried these changes locally with Bitcoin Core 28.0 and the tests pass :sparkles:
